server:
  port: 8260
#  servlet:
#    context-path: /api

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:     
  application:
    name: LEAGUE-GATEWAY
  cloud:
    discovery:
      enabled: true
    gateway:
      server:
        webflux:
          discovery:
             locator:
               enabled: true
               lower-case-service-id: true
          routes:
           - id: ORDER-SERVICE 
             uri: lb://ORDER-SERVICE
             predicates:
              - Path=/api/1.0/**

           - id: REPORT-GENERATION 
             uri: lb://REPORT-GENERATION
             predicates:
              - Path=/api/1.0/**          
